# UTS-2 My Songs for You


Song: Halfway There - Big Time Rush

{{< video https://youtu.be/v-87vtFhCqI?si=UXjaiaRZ3zpD3FCh >}} 

Lagu ini saya tujukan untuk teman - teman saya yg sedang berjuang dan juga untuk saya sendiri. lagu ini membawa pesan bahwa hidup itu tidak sesederhana keinginan, jika kita tidak mencoba kita tidak akan jatuh namun, kita juga tidak akan pernah melangkah lebih jauh. lagu ini juga membawa pesan kebersamaan seperti pada lirik "so we take what comes and we keep on going, leaning on each other's shoulders Then we turn around, And see we've come so far somehow" kita menerima apapun yg datang dan terus melangkah bersama, saling menopang satu sama lain dan ketika ketika mengingat kembali perjuangan kita, kita sudah sejauh ini tanpa disadari. 

## lyrics

[Verse 1]
If we never flew, we would never fall
If the world was ours, we would have it all
But the life we live, isn't so simplistic
You just don't get what you want

[Pre-Chorus]
So we take what comes and we keep on going
Leaning on each other's shoulders
Then we turn around
And see we've come so far somehow

[Chorus]
We're halfway there, we're looking good now
Nothing's gonna get in the way
We're halfway there and looking back now
I never thought that I'd ever say

[Post-Chorus]
We're halfway there!
We're halfway there!

[Verse 2]
When the chips are down back against the wall
Got no more to give 'cause we gave it all
Seems like going the distance is unrealistic
But we're too far from the start

[Pre-Chorus]
So we take what comes and we keep on going
Leaning on each other's shoulders
Then we turn around
And see we've come so far somehow

[Chorus]
We're halfway there, we're looking good now
Nothing's gonna get in the way
We're halfway there and looking back now
I never thought that I'd ever say

[Post-Chorus]
We're halfway there!
We're halfway there!

[Verse 3]
How you ever gonna reach the stars
If you never get off the ground?
And you'll always be where you are
If you let life knock you down

[Chorus]
We're halfway there, we're looking good now
Nothing's gonna get in the way
We're halfway there and looking back now
I never thought that I'd ever say

[Post-Chorus]
We're halfway there! (Oh, we're halfway there; halfway there)
We're halfway there! (Oh, we're halfway there; halfway there)

(Oh, we're halfway there; halfway there)